namespace Microsoft.Cse.SpeechToSpeech.UI.Model
{
    using System.Collections.Generic;

    public static class VoiceList
    {
        public static IEnumerable<VoiceLanguage> Voices
        {
            get => voices;
        }

        private static VoiceLanguage[] voices = {
            new VoiceLanguage() { Locale = "ar-EG*", Language="Arabic (Egypt)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (ar-EG, Hoda)" },
            new VoiceLanguage() { Locale = "ar-SA", Language="Arabic (Saudi Arabia)", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (ar-SA, Naayf)" },
            new VoiceLanguage() { Locale = "bg-BG", Language="Bulgarian", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (bg-BG, Ivan)" },
            new VoiceLanguage() { Locale = "ca-ES", Language="Catalan (Spain)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (ca-ES, HerenaRUS)" },
            new VoiceLanguage() { Locale = "cs-CZ", Language="Czech", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (cs-CZ, Jakub)" },
            new VoiceLanguage() { Locale = "da-DK", Language="Danish", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (da-DK, HelleRUS)"},
            new VoiceLanguage() { Locale = "de-AT", Language="German (Austria)", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (de-AT, Michael)"},
            new VoiceLanguage() { Locale = "de-CH", Language="German (Switzerland)", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (de-CH, Karsten)" },
            new VoiceLanguage() { Locale = "de-DE", Language="German (Germany)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (de-DE, Hedda)" },
            new VoiceLanguage() { Locale = "de-DE", Language="German (Germany)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (de-DE, HeddaRUS)" },
            new VoiceLanguage() { Locale = "de-DE", Language="German (Germany)", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (de-DE, Stefan, Apollo)" },
            new VoiceLanguage() { Locale = "el-GR", Language="Greek", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (el-GR, Stefanos)" },
            new VoiceLanguage() { Locale = "en-AU", Language="English (Australia)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (en-AU, Catherine)" },
            new VoiceLanguage() { Locale = "en-AU", Language="English (Australia)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (en-AU, HayleyRUS)" },
            new VoiceLanguage() { Locale = "en-CA", Language="English (Canada)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (en-CA, Linda)" },
            new VoiceLanguage() { Locale = "en-CA", Language="English (Canada)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (en-CA, HeatherRUS)" },
            new VoiceLanguage() { Locale = "en-GB", Language="English (UK)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (en-GB, Susan, Apollo)" },
            new VoiceLanguage() { Locale = "en-GB", Language="English (UK)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (en-GB, Susan, HazelRUS)" },
            new VoiceLanguage() { Locale = "en-GB", Language="English (UK)", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (en-GB, George, Apollo)" },
            new VoiceLanguage() { Locale = "en-IE", Language="English (Ireland)", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (en-IE, Sean)"},
            new VoiceLanguage() { Locale = "en-IN", Language="English (India)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (en-IN, Heera, Apollo)" },
            new VoiceLanguage() { Locale = "en-IN", Language="English (India)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (en-IN, Heera, PriyaRUS)" },
            new VoiceLanguage() { Locale = "en-IN", Language="English (India)", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (en-IN, Ravi, Apollo)" },
            new VoiceLanguage() { Locale = "en-US", Language="English (US)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (en-US, ZiraRUS)" },
            new VoiceLanguage() { Locale = "en-US", Language="English (US)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (en-US, JessaRUS)" },
            new VoiceLanguage() { Locale = "en-US", Language="English (US)", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (en-US, BenjaminRUS)" },
            new VoiceLanguage() { Locale = "en-US", Language="English (US)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (en-US, Jessa24kRUS)" },
            new VoiceLanguage() { Locale = "en-US", Language="English (US)", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (en-US, Guy24kRUS)" },
            new VoiceLanguage() { Locale = "es-ES", Language="Spanish (Spain)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (es-ES, Laura, Apollo)" },
            new VoiceLanguage() { Locale = "es-ES", Language="Spanish (Spain)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (es-ES, HelenaRUS)" },
            new VoiceLanguage() { Locale = "es-ES", Language="Spanish (Spain)", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (es-ES, Pablo, Apollo)" },
            new VoiceLanguage() { Locale = "es-MX", Language="Spanish (Mexico)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (es-MX, HildaRUS)" },
            new VoiceLanguage() { Locale = "es-MX", Language="Spanish (Mexico)", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (es-MX, Raul, Apollo)" },
            new VoiceLanguage() { Locale = "fi-FI", Language="Finnish", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (fi-FI, HeidiRUS)" },
            new VoiceLanguage() { Locale = "fr-CA", Language="French (Canada)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (fr-CA, Caroline)" },
            new VoiceLanguage() { Locale = "fr-CA", Language="French (Canada)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (fr-CA, HarmonieRUS)" },
            new VoiceLanguage() { Locale = "fr-CH", Language="French (Switzerland)", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (fr-CH, Guillaume)" },
            new VoiceLanguage() { Locale = "fr-FR", Language="French (France)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (fr-FR, Julie, Apollo)" },
            new VoiceLanguage() { Locale = "fr-FR", Language="French (France)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (fr-FR, Julie, HortenseRUS)" },
            new VoiceLanguage() { Locale = "fr-FR", Language="French (France)", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (fr-FR, Paul, Apollo)" },
            new VoiceLanguage() { Locale = "he-IL", Language="Hebrew (Israel)", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (he-IL, Asaf)" },
            new VoiceLanguage() { Locale = "hi-IN", Language="Hindi (India)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (hi-IN, Kalpana, Apollo)" },
            new VoiceLanguage() { Locale = "hi-IN", Language="Hindi (India)", Gender = Gender.Female, VoiceName = "Microsoft Server Speech Text to Speech Voice (hi-IN, Kalpana)" },
            new VoiceLanguage() { Locale = "hi-IN", Language="Hindi (India)", Gender = Gender.Male, VoiceName = "Microsoft Server Speech Text to Speech Voice (hi-IN, Hemant)" },
            new VoiceLanguage() { Locale = "hr-HR", Language="Croatian", Gender = Gender.Male, VoiceName = "Microsoft Server Speech Text to Speech Voice (hr-HR, Matej)" },
            new VoiceLanguage() { Locale = "hu-HU", Language="Hungarian", Gender = Gender.Male, VoiceName = "Microsoft Server Speech Text to Speech Voice (hu-HU, Szabolcs)" },
            new VoiceLanguage() { Locale = "id-ID", Language="Indonesian", Gender = Gender.Male, VoiceName = "Microsoft Server Speech Text to Speech Voice (id-ID, Andika)" },
            new VoiceLanguage() { Locale = "it-IT", Language="Italian", Gender = Gender.Male, VoiceName = "Microsoft Server Speech Text to Speech Voice (it-IT, Cosimo, Apollo)" },
            new VoiceLanguage() { Locale = "it-IT", Language="Italian", Gender = Gender.Female, VoiceName = "Microsoft Server Speech Text to Speech Voice (it-IT, LuciaRUS)" },
            new VoiceLanguage() { Locale = "ja-JP", Language="Japanese", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (ja-JP, Ayumi, Apollo)"},
            new VoiceLanguage() { Locale = "ja-JP", Language="Japanese", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (ja-JP, Ichiro, Apollo)"},
            new VoiceLanguage() { Locale = "ja-JP", Language="Japanese", Gender = Gender.Female, VoiceName = "Microsoft Server Speech Text to Speech Voice (ja-JP, HarukaRUS)"},
            new VoiceLanguage() { Locale = "ko-KR", Language="Korean", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (ko-KR, HeamiRUS)"},
            new VoiceLanguage() { Locale = "ms-MY", Language="Malay", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (ms-MY, Rizwan)" },
            new VoiceLanguage() { Locale = "nb-NO", Language="Norwegian", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (nb-NO, HuldaRUS)"},
            new VoiceLanguage() { Locale = "nl-NL", Language="Dutch", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (nl-NL, HannaRUS)" },
            new VoiceLanguage() { Locale = "pl-PL", Language="Polish", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (pl-PL, PaulinaRUS)" },
            new VoiceLanguage() { Locale = "pt-BR", Language="Portuguese (Brazil)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (pt-BR, HeloisaRUS)" },
            new VoiceLanguage() { Locale = "pt-BR", Language="Portuguese (Brazil)", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (pt-BR, HeloisaRUS)" },
            new VoiceLanguage() { Locale = "pt-PT", Language="Portuguese (Portugal)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (pt-PT, HeliaRUS)" },
            new VoiceLanguage() { Locale = "ro-RO", Language="Romanian", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (ro-RO, Andrei)" },
            new VoiceLanguage() { Locale = "ru-RU", Language="Russian", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (ru-RU, Irina, Apollo)" },
            new VoiceLanguage() { Locale = "ru-RU", Language="Russian", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (ru-RU, Pavel, Apollo)" },
            new VoiceLanguage() { Locale = "ru-RU", Language="Russian", Gender = Gender.Female, VoiceName = "Microsoft Server Speech Text to Speech Voice (ru-RU, EkaterinaRUS)" },
            new VoiceLanguage() { Locale = "sk-SK", Language="Slovak", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (sk-SK, Filip)" },
            new VoiceLanguage() { Locale = "sl-SI", Language="Slovenian", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (sl-SI, Lado)" },
            new VoiceLanguage() { Locale = "sv-SE", Language="Swedish", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (sv-SE, HedvigRUS)" },
            new VoiceLanguage() { Locale = "ta-IN", Language="Tamil (India)", Gender = Gender.Male, VoiceName = "Microsoft Server Speech Text to Speech Voice (ta-IN, Valluvar)" },
            new VoiceLanguage() { Locale = "te-IN", Language="Telugu (India)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (te-IN, Chitra)" },
            new VoiceLanguage() { Locale = "th-TH", Language="Thai", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (th-TH, Pattara)" },
            new VoiceLanguage() { Locale = "tr-TR", Language="Turkish", Gender = Gender.Female, VoiceName = "Microsoft Server Speech Text to Speech Voice (tr-TR, SedaRUS)" },
            new VoiceLanguage() { Locale = "vi-VN", Language="Vietnamese", Gender = Gender.Male, VoiceName = "Microsoft Server Speech Text to Speech Voice (vi-VN, An)" },
            new VoiceLanguage() { Locale = "zh-CN", Language="Chinese (Mainland)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (zh-CN, HuihuiRUS)" },
            new VoiceLanguage() { Locale = "zh-CN", Language="Chinese (Mainland)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (zh-CN, Yaoyao, Apollo)"},
            new VoiceLanguage() { Locale = "zh-CN", Language="Chinese (Mainland)", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (zh-CN, Kangkang, Apollo)" },
            new VoiceLanguage() { Locale = "zh-HK", Language="Chinese (Hong Kong)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (zh-HK, Tracy, Apollo)" },
            new VoiceLanguage() { Locale = "zh-HK", Language="Chinese (Hong Kong)", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (zh-HK, TracyRUS)" },
            new VoiceLanguage() { Locale = "zh-HK", Language="Chinese (Hong Kong)", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (zh-HK, Danny, Apollo)" },
            new VoiceLanguage() { Locale = "zh-TW", Language="Arabic", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (zh-TW, Yating, Apollo)" },
            new VoiceLanguage() { Locale = "zh-TW", Language="Arabic", Gender = Gender.Female, VoiceName ="Microsoft Server Speech Text to Speech Voice (zh-TW, HanHanRUS)" },
            new VoiceLanguage() { Locale = "zh-TW", Language="Arabic", Gender = Gender.Male, VoiceName ="Microsoft Server Speech Text to Speech Voice (zh-TW, Zhiwei, Apollo)" }
        };
    }
}
